"""T2c — forced-prefix entity readout on the C2 matched activation pairs (PLAN.md round 3b; AV forward only). PRIMARY.

  uv run python overnight/t2c_entity.py

Prefixes (frozen in PLAN, one noun per C2 template, index = template_id):
  p1 = '<explanation>\nThe {noun} mentioned in the passage is'   (kill statistic)
  p2 = '<explanation>\nThe passage mentions the {noun}'          (held-out confirmation)
Candidates: the pair's own entities e_a, e_b from c2_pairs.csv, scored as ' ' + e (summed log-prob of every
token; token counts recorded; per-token mean also reported). Activations h_a, h_b from out/c2_acts.npz,
h_0 = no injection (raw marker embedding, asserted by Prefix.inject). Injection and prefill exactly as
round-3 t2_prefix.Prefix (marker row replaced by v*150/||v||, asserted).
Score D(h) = lp(e_a | p, h) - lp(e_b | p, h). Per pair: D(h_a), D(h_b), D(h_0).
Kill T2c (pre-registered): CI95 (cluster bootstrap by template, 10 clusters, 1000 draws, seed 0) of mean
[D(h_a) - D(h_b)] under p1 <= 0 -> MET; INCONCLUSIVE if the CI straddles 0.
Nothing generated by the AV appears in any prefix or candidate.
"""
from __future__ import annotations

import json
import sys
import time
import traceback
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from overnight import nla_lib as L  # noqa: E402  (sets MPS env first)
from overnight.t2_prefix import Prefix  # noqa: E402  (Settings created inside its main(); import-safe, checked in U0)
from overnight.t1_arprobe import auroc  # noqa: E402

import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402
import torch  # noqa: E402

NOUNS = ["city", "ingredient", "time", "instrument", "metal", "city", "illness", "profession", "animal", "subject"]
P1 = "<explanation>\nThe {noun} mentioned in the passage is"
P2 = "<explanation>\nThe passage mentions the {noun}"
PREFIXES = {"p1": P1, "p2": P2}
N_BOOT, SEED = 1000, 0
MIN_PAIRS = 30


def boot_frac(ind, clusters):
    """Cluster-bootstrap CI of a proportion (indicator array)."""
    return L.cluster_bootstrap_mean(np.asarray(ind, dtype=float), clusters, n_boot=N_BOOT, seed=SEED)


def boot_auroc_by_cluster(pos, neg, clusters, seed=SEED):
    """Paired AUROC of pos (D(h_a)) vs neg (D(h_b)); bootstrap resampling whole clusters (templates) and, separately, pairs."""
    pos = np.asarray(pos, float); neg = np.asarray(neg, float); cl = np.asarray(clusters)
    uniq = np.unique(cl); rng = np.random.default_rng(seed)
    vt = []
    for _ in range(N_BOOT):
        pick = rng.choice(uniq, size=len(uniq), replace=True)
        idx = np.concatenate([np.where(cl == u)[0] for u in pick])
        vt.append(auroc(pos[idx], neg[idx]))
    rng = np.random.default_rng(seed); n = len(pos)
    vp = [auroc(pos[idx], neg[idx]) for idx in rng.integers(0, n, size=(N_BOOT, n))]
    return {"auroc": auroc(pos, neg), "lo_tpl": float(np.percentile(vt, 2.5)), "hi_tpl": float(np.percentile(vt, 97.5)),
            "lo_pair": float(np.percentile(vp, 2.5)), "hi_pair": float(np.percentile(vp, 97.5)), "n": int(n), "n_clusters": int(len(uniq))}


def stats_for(ok: pd.DataFrame, px: str, pt: bool) -> dict:
    """All statistics 1-5 for prefix px; pt=True uses per-token-normalised log-probs."""
    sfx = "_pt" if pt else ""
    Da, Db, D0 = ok[f"{px}_D_a{sfx}"].values, ok[f"{px}_D_b{sfx}"].values, ok[f"{px}_D_0{sfx}"].values
    cl = ok.template_id.values
    d = {}
    d["donor"] = L.cluster_bootstrap_mean(Da - Db, cl, n_boot=N_BOOT, seed=SEED)
    d["donor_frac_pos"] = boot_frac(Da - Db > 0, cl)
    d["raw_both"] = boot_frac((Da > 0) & (Db < 0), cl); d["raw_a"] = boot_frac(Da > 0, cl); d["raw_b"] = boot_frac(Db < 0, cl)
    Dac, Dbc = Da - D0, Db - D0
    d["cen_both"] = boot_frac((Dac > 0) & (Dbc < 0), cl); d["cen_a"] = boot_frac(Dac > 0, cl); d["cen_b"] = boot_frac(Dbc < 0, cl)
    # within-pair choice accuracy pooled over 80 activations: argmax_c lp(c|p,h) == own entity  <=>  D(h_a)>0 for side a, D(h_b)<0 for side b
    acc_raw = np.concatenate([Da > 0, Db < 0]); acc_cen = np.concatenate([Dac > 0, Dbc < 0]); cl2 = np.concatenate([cl, cl])
    d["acc_raw"] = boot_frac(acc_raw, cl2); d["acc_cen"] = boot_frac(acc_cen, cl2)
    d["auroc"] = boot_auroc_by_cluster(Da, Db, cl)
    d["mean_D_a"] = float(Da.mean()); d["mean_D_b"] = float(Db.mean()); d["mean_D_0"] = float(D0.mean())
    d["prior_frac_pos"] = float((D0 > 0).mean())
    return d


def main():
    S = L.Settings("t2c", nouns=NOUNS, prefixes=PREFIXES, candidate_rule="' ' + entity, tokenised separately (add_special_tokens=False) and appended after the prefill; summed log-prob of all candidate tokens; per-token mean also reported",
                   no_injection="marker row left as the raw embedding of token 149705 (asserted in Prefix.inject)", injection="marker row := v*150/||v|| exactly as nla_lib.AV.verbalize / t2_prefix.Prefix",
                   score="D(h) = lp(e_a|p,h) - lp(e_b|p,h)", kill="CI95 (cluster bootstrap by template, 1000 draws, seed 0) of mean [D(h_a) - D(h_b)] under p1 <= 0 -> MET; INCONCLUSIVE if straddles 0 or n_pairs < 30",
                   n_boot=N_BOOT, seed=SEED, min_pairs=MIN_PAIRS)
    timings = {}
    pairs = pd.read_csv(L.OVERNIGHT / "c2_pairs.csv").sort_values("pair_id").reset_index(drop=True)
    assert len(pairs) == 40 and pairs.error.isna().all()
    H = np.load(L.OUT / "c2_acts.npz")["H"]; assert H.shape == (40, 2, 3584)
    desc = [json.loads(ln) for ln in (L.OVERNIGHT / "c2_descriptions.jsonl").read_text().splitlines() if ln.strip()]
    assert len(desc) == 80
    own_rate = pd.DataFrame(desc).groupby("template_id").mentions_own.apply(lambda s: float(s.fillna(False).astype(bool).mean()))

    t0 = time.time()
    av = L.AV()
    timings["av_load_s"] = time.time() - t0
    P = Prefix(av)
    S.update(prompt_tokens=int(P.ids.shape[1]), marker_pos=P.inj_pos)
    noinj: dict[tuple[str, str], tuple[float, int]] = {}

    def lp0(prefill, cand):
        k = (prefill, cand)
        if k not in noinj:
            noinj[k] = P.cont_logprob(None, prefill, cand)
        return noinj[k]

    rows = []
    t0 = time.time()
    for r in pairs.itertuples():
        i = r.pair_id; noun = NOUNS[r.template_id]
        ha, hb = torch.from_numpy(H[i, 0]), torch.from_numpy(H[i, 1])
        ca, cb = " " + r.entity_a, " " + r.entity_b
        row = {"pair_id": i, "template_id": r.template_id, "noun": noun, "entity_a": r.entity_a, "entity_b": r.entity_b, "context_a": r.context_a, "context_b": r.context_b,
               "dist_to_end": r.dist_to_end, "cos_ha_hb": r.cos_ha_hb, "mentions_own_a": r.mentions_own_a, "mentions_own_b": r.mentions_own_b, "C2_M": r.M, "error": ""}
        try:
            for px, tpl in PREFIXES.items():
                pre = tpl.format(noun=noun)
                row[f"{px}_prefix"] = pre
                la_a, na = P.cont_logprob(ha, pre, ca); lb_a, nb = P.cont_logprob(ha, pre, cb)
                la_b, _ = P.cont_logprob(hb, pre, ca); lb_b, _ = P.cont_logprob(hb, pre, cb)
                la_0, _ = lp0(pre, ca); lb_0, _ = lp0(pre, cb)
                row.update({f"{px}_n_tok_a": na, f"{px}_n_tok_b": nb,
                            f"{px}_lp_a_given_ha": la_a, f"{px}_lp_b_given_ha": lb_a, f"{px}_lp_a_given_hb": la_b, f"{px}_lp_b_given_hb": lb_b, f"{px}_lp_a_given_h0": la_0, f"{px}_lp_b_given_h0": lb_0,
                            f"{px}_D_a": la_a - lb_a, f"{px}_D_b": la_b - lb_b, f"{px}_D_0": la_0 - lb_0,
                            f"{px}_D_a_pt": la_a / na - lb_a / nb, f"{px}_D_b_pt": la_b / na - lb_b / nb, f"{px}_D_0_pt": la_0 / na - lb_0 / nb})
                row[f"{px}_donor"] = row[f"{px}_D_a"] - row[f"{px}_D_b"]; row[f"{px}_donor_pt"] = row[f"{px}_D_a_pt"] - row[f"{px}_D_b_pt"]
                row[f"{px}_D_a_cen"] = row[f"{px}_D_a"] - row[f"{px}_D_0"]; row[f"{px}_D_b_cen"] = row[f"{px}_D_b"] - row[f"{px}_D_0"]
        except Exception:
            row["error"] = traceback.format_exc(); L.log(f"T2c FAILED on pair {i}")
        rows.append(row)
        if i % 10 == 9:
            L.log(f"pair {i + 1}/40, forwards {P.n_forward} ({(time.time() - t0) / max(1, P.n_forward):.2f}s each)")
    timings["av_s_per_forward"] = (time.time() - t0) / max(1, P.n_forward); timings["n_av_forward"] = P.n_forward
    av.free()
    df = pd.DataFrame(rows)
    df.to_csv(L.OVERNIGHT / "t2c_pairs.csv", index=False)
    ok = df[df.error == ""].reset_index(drop=True)

    ST = {(px, pt): stats_for(ok, px, pt) for px in PREFIXES for pt in [False, True]}
    k = ST[("p1", False)]
    out = L.outcome_ci_at_or_below(k["donor"], 0.0, min_n=MIN_PAIRS)

    def fm(c, d=4):
        return f"{c['mean']:.{d}f} [{c['lo']:.{d}f},{c['hi']:.{d}f}]"

    L.append_disconfirmation("T2c", "T2c", "CI95 (cluster bootstrap by template) of mean [D(h_a) − D(h_b)] under p1 '<explanation>\\nThe {noun} mentioned in the passage is', D = lp(' e_a') − lp(' e_b'), ≤ 0",
                             f"mean donor sensitivity={fm(k['donor'])} n={k['donor']['n']} n_templates={k['donor']['n_clusters']}; frac>0={k['donor_frac_pos']['mean']:.3f}; both-correct raw {k['raw_both']['mean']:.3f} prior-centred {k['cen_both']['mean']:.3f}; "
                             f"choice accuracy raw {fm(k['acc_raw'], 3)} centred {fm(k['acc_cen'], 3)} (80 activations); paired AUROC D(h_a) vs D(h_b) {k['auroc']['auroc']:.4f} [{k['auroc']['lo_tpl']:.4f},{k['auroc']['hi_tpl']:.4f}] by template; "
                             f"prior D(h_0)>0 frac {k['prior_frac_pos']:.3f}; p2 donor {fm(ST[('p2', False)]['donor'])} both-correct raw {ST[('p2', False)]['raw_both']['mean']:.3f}",
                             out, "MET would mean the upstream entity is not readable from the final-token activation by forced prefix")

    # ---------------- summary
    lines = ["# T2c summary — forced-prefix entity readout on the C2 matched activation pairs (AV forward only) — PRIMARY", "",
             f"git {L.git_hash()[:8]}; settings in t2c_settings.json; rows in t2c_pairs.csv (one row per pair, every lp and D for both prefixes)", "",
             f"- pairs {len(df)} (errors {int((df.error != '').sum())}); templates {ok.template_id.nunique()}; AV forwards {timings['n_av_forward']} ({timings['av_s_per_forward']:.2f} s each); prompt {int(P.ids.shape[1])} tokens, marker at {P.inj_pos}",
             f"- prefixes: p1 = `{P1}`; p2 = `{P2}`; nouns by template = {NOUNS}",
             f"- candidate token counts (' ' + entity): a: {dict(ok.p1_n_tok_a.value_counts().sort_index())}, b: {dict(ok.p1_n_tok_b.value_counts().sort_index())}",
             "- what each number is: *donor sensitivity* = activation dependence (prior cancels); *prior-centred* subtracts D(h_0), the no-injection prompt-only preference; nothing in any prefix or candidate was generated by the AV",
             "", "## Kill T2c (p1, summed log-prob)", "",
             f"- mean [D(h_a) − D(h_b)]: {fm(k['donor'])} n={k['donor']['n']} clusters={k['donor']['n_clusters']} templates; threshold ≤ 0 → **{out}**",
             "", "## All statistics, both prefixes, summed and per-token-normalised (CIs: cluster bootstrap by template; AUROC CI by template and by pair)", "",
             "| prefix | norm | 1. donor sens. mean [CI] | frac>0 | 2. raw both-correct | raw D(h_a)>0 | raw D(h_b)<0 | 3. centred both-correct | centred a | centred b | 4. choice acc raw (80) | choice acc centred (80) | 5. AUROC D(h_a) vs D(h_b) [tpl CI] [pair CI] | mean D(h_a) | mean D(h_b) | mean D(h_0) | frac D(h_0)>0 |",
             "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for (px, pt), s in ST.items():
        lines.append(f"| {px} | {'per-token' if pt else 'summed'} | {fm(s['donor'])} | {s['donor_frac_pos']['mean']:.3f} | {fm(s['raw_both'], 3)} | {s['raw_a']['mean']:.3f} | {s['raw_b']['mean']:.3f} | {fm(s['cen_both'], 3)} | {s['cen_a']['mean']:.3f} | {s['cen_b']['mean']:.3f} | "
                     f"{fm(s['acc_raw'], 3)} | {fm(s['acc_cen'], 3)} | {s['auroc']['auroc']:.4f} [{s['auroc']['lo_tpl']:.4f},{s['auroc']['hi_tpl']:.4f}] [{s['auroc']['lo_pair']:.4f},{s['auroc']['hi_pair']:.4f}] | {s['mean_D_a']:.3f} | {s['mean_D_b']:.3f} | {s['mean_D_0']:.3f} | {s['prior_frac_pos']:.3f} |")
    lines += ["", "## 6. Per-template table (p1 summed; own-entity mention rate from C2 descriptions)", "",
              "| template | noun | n pairs | mean donor sens. p1 | frac>0 | both-correct raw p1 | both-correct centred p1 | mean donor sens. p2 | both-correct raw p2 | own-entity mention rate (C2) | mean C2 M | mean cos(h_a,h_b) |", "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for ti, g in ok.groupby("template_id"):
        lines.append(f"| {ti} | {NOUNS[ti]} | {len(g)} | {g.p1_donor.mean():.4f} | {(g.p1_donor > 0).mean():.2f} | {((g.p1_D_a > 0) & (g.p1_D_b < 0)).mean():.2f} | {((g.p1_D_a_cen > 0) & (g.p1_D_b_cen < 0)).mean():.2f} | "
                     f"{g.p2_donor.mean():.4f} | {((g.p2_D_a > 0) & (g.p2_D_b < 0)).mean():.2f} | {own_rate.get(ti, float('nan')):.2f} | {g.C2_M.mean():.4f} | {g.cos_ha_hb.mean():.4f} |")
    for px in PREFIXES:
        lines += ["", f"## Full 40-row table — {px} = `{PREFIXES[px]}` (summed log-probs)", "",
                  "| pair | tpl | e_a | e_b | n_tok a/b | lp(a|h_a) | lp(b|h_a) | lp(a|h_b) | lp(b|h_b) | lp(a|h_0) | lp(b|h_0) | D(h_a) | D(h_b) | D(h_0) | donor | D(h_a)−D(h_0) | D(h_b)−D(h_0) | own-mention a/b (C2) |", "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
        for r in df.itertuples():
            if r.error:
                lines.append(f"| {r.pair_id} | {r.template_id} | {r.entity_a} | {r.entity_b} | ERROR | | | | | | | | | | | | | |"); continue
            g = lambda c: getattr(r, f"{px}_{c}")  # noqa: E731
            lines.append(f"| {r.pair_id} | {r.template_id} | {r.entity_a} | {r.entity_b} | {g('n_tok_a')}/{g('n_tok_b')} | {g('lp_a_given_ha'):.2f} | {g('lp_b_given_ha'):.2f} | {g('lp_a_given_hb'):.2f} | {g('lp_b_given_hb'):.2f} | {g('lp_a_given_h0'):.2f} | {g('lp_b_given_h0'):.2f} | "
                         f"{g('D_a'):+.2f} | {g('D_b'):+.2f} | {g('D_0'):+.2f} | {g('donor'):+.2f} | {g('D_a_cen'):+.2f} | {g('D_b_cen'):+.2f} | {r.mentions_own_a}/{r.mentions_own_b} |")
    lines.append("")
    (L.OVERNIGHT / "t2c_summary.md").write_text("\n".join(lines) + "\n")
    S.finish(timings=timings, n_pairs=len(df), n_errors=int((df.error != "").sum()), kill_T2c={"ci": k["donor"], "outcome": out},
             stats={f"{px}_{'pt' if pt else 'sum'}": s for (px, pt), s in ST.items()})
    L.log(f"T2c done: donor={k['donor']['mean']:.4f} [{k['donor']['lo']:.4f},{k['donor']['hi']:.4f}] -> {out}; both-correct raw {k['raw_both']['mean']:.3f}; acc raw {k['acc_raw']['mean']:.3f}")


if __name__ == "__main__":
    main()
